version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: