name: CI

on:
  push:
    branches: [main, feat-*]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.19

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Biome check (lint + format)
        run: bun run check

      - name: Build application
        run: bun run build

      - name: Type check
        run: |
          cd apps/frontend
          bunx tsc --noEmit

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.19
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Run security audit
        run: |
          # Bun doesn't have built-in audit yet, skip for now
          echo "Security audit skipped - Bun doesn't have built-in audit command yet"